### ISSUE TITLE
Won't start on Ubuntu 17.10

### ISSUE THREAD

**Issue by Spiffyk** [yancharkin/games_nebula#22] opened 2018-04-12 16:27 UTC
Games Nebula crashes on startup on my Ubuntu 17.10 with the following output. I tried the latest release as well as the latest `master` from git, both yield the same result.

```
Not authorized on GOG
Traceback (most recent call last):
  File "games_nebula.py", line 6664, in <module>
    sys.exit(main())
  File "games_nebula.py", line 6660, in main
    app = GUI()
  File "games_nebula.py", line 133, in __init__
    self.create_main_window()
  File "games_nebula.py", line 317, in create_main_window
    self.create_goglib_tab_content('auto')
  File "games_nebula.py", line 409, in create_goglib_tab_content
    _("Authorize?")
  File "games_nebula.py", line 174, in simple_question
    content_area_label = content_area.get_children()[0].get_children()[0].get_children()[1]
AttributeError: 'Image' object has no attribute 'get_children'
```

**Comment by yancharkin** [comment] 2018-04-12 16:49
Looks like something changed in gtk3 (or in Ubuntu). Just comment or delete lines 152, 153, 174 and 175 in 'games_nebula.py'.

**Comment by Patola** [comment] 2018-04-13 00:04
I am using Ubuntu 17.10 and I have not needed to change anything for games_nebula to launch

**Comment by yancharkin** [comment] 2018-04-13 09:07
@Patola That's because you are already authorized and @Spiffyk is not.

**Comment by Yupy** [comment] 2018-04-13 10:49
Same here (Linux Mint 18.3 Cinnamon), it wont start I get this error:

`Traceback (most recent call last):
  File "games_nebula.py", line 6593, in <module>
    sys.exit(main())
  File "games_nebula.py", line 6589, in main
    app = GUI()
  File "games_nebula.py", line 128, in __init__
    self.monitors_list, self.monitor_primary = monitors.get_monitors()
  File "/home/Yupy/Documente/Games-Nebula/modules/monitors.py", line 23, in get_monitors
    n_monitors = display.get_n_monitors()
AttributeError: 'X11Display' object has no attribute 'get_n_monitors'
`

**Comment by yancharkin** [comment] 2018-04-13 10:55
@Yupy It's not exactly the same, but I'm aware of this problem. I'll push changes to master and probably publish new release today. Please check and report later.

**Comment by yancharkin** [comment] 2018-04-13 11:35
@Spiffyk, @Yupy Issue should be fixed in master, please test.

**Comment by Yupy** [comment] 2018-04-14 17:27
Thank you very much @yancharkin, I can confirm it works!
Thanks again.

**Comment by yancharkin** [comment] 2018-04-24 12:49
@Spiffyk I believe this issue now fixed. Report if you still have troubles launching app.

**Closed as completed by yancharkin** 2018-04-24 12:49 UTC
