### ISSUE TITLE
local variable 'ini_file' referenced before assignment

### ISSUE THREAD

**Issue by sgsaenger** [yancharkin/games_nebula#24] opened 2018-05-01 09:02 UTC
In `goglib_install_game` of `games_nebula.py`, you seem to expect some `*.ini` files to be present for all scummvm games.
At least for Riven, this file is not present and thus throws the `UnboundLocalError` from the title.

**Comment by yancharkin** [comment] 2018-05-01 10:47
It took me sometime to find out what's wrong. Looks like new format of GOG installers is a culprit. Can you extract Riven's installer and post the list of it's content here?

**Comment by yancharkin** [comment] 2018-05-01 12:34
Probably I was wrong, most likely Riven's installer use old format. If so, error emerge because some GOG installers have different internal structure. Configuration file (*.ini) present in all scummvm games that I own. It's relatively easy to fix this issue, but GOG started to publish new installers, which require different solution. Right now both old and new installers exists. Honestly, I'm not sure how to deal with this situation. Anyway, I'd like to see the list of Riven's installer content.

**Comment by sgsaenger** [comment] 2018-05-01 15:17
Had to redownload it first, but here it is. Guess you're looking for `app/__support/app/rivensvm.ini`?

```
.
├── app
│   ├── a_Data.MHK
│   ├── a_Sounds.MHK
│   ├── b2_data.MHK
│   ├── b_Data.MHK
│   ├── b_Sounds.MHK
│   ├── Extras.MHK
│   ├── g_Data.MHK
│   ├── goggame-1207658819.hashdb
│   ├── goggame-1207658819.ico
│   ├── goggame-1207658819.info
│   ├── goggame-1207658819.script
│   ├── g_Sounds.MHK
│   ├── j_Data1.MHK
│   ├── j_Data2.MHK
│   ├── j_Sounds.MHK
│   ├── manual.pdf
│   ├── o_Data.MHK
│   ├── o_Sounds.MHK
│   ├── p_Data.MHK
│   ├── p_Sounds.MHK
│   ├── r_Data.MHK
│   ├── Readme.txt
│   ├── Riven.exe
│   ├── r_Sounds.MHK
│   ├── ScummVM
│   │   ├── AUTHORS.txt
│   │   ├── COPYING.BSD.txt
│   │   ├── COPYING.FREEFONT.txt
│   │   ├── COPYING.LGPL.txt
│   │   ├── COPYING.txt
│   │   ├── COPYRIGHT.txt
│   │   ├── doc
│   │   │   └── <localized readmes here>
│   │   ├── graphics
│   │   │   ├── left.bmp
│   │   │   └── scummvm-install.ico
│   │   ├── migration.bat
│   │   ├── migration.txt
│   │   ├── NEWS.txt
│   │   ├── README-SDL.txt
│   │   ├── README.txt
│   │   ├── scummvm.exe
│   │   ├── SDL2.dll
│   │   └── WinSparkle.dll
│   ├── __support
│   │   ├── app
│   │   │   └── rivensvm.ini
│   │   └── scriptinterpreter.exe
│   ├── t_Data1.MHK
│   ├── t_Data2.MHK
│   ├── t_Sounds.MHK
│   └── webcache.zip
└── tmp
    └── <looks like installer stuff here>
```

**Comment by yancharkin** [comment] 2018-05-01 15:26
Yes, that's a correct file. Are you using vanilla innoextract or [this fork](https://github.com/immi101/innoextract/tree/gogextract)?

**Comment by sgsaenger** [comment] 2018-05-01 15:30
Vanilla

**Comment by yancharkin** [comment] 2018-05-01 21:28
I believe the issue is fixed for old installers (as Riven's installer), report if not.
For new installers I have to find a new way to extract data.

**Comment by yancharkin** [comment] 2018-05-04 13:09
@sgsaenger Does it work for you now?

**Comment by sgsaenger** [comment] 2018-05-04 17:19
sorry it took a while, the installation works very well!
only the scummvm argument is wrong ('rivensvm' instead of just 'riven'), but this i can fix by hand for now.
will try to figure out a safer way to determine this.

**Comment by yancharkin** [comment] 2018-05-04 18:58
@sgsaenger  Now it should work fine. Please test.

**Comment by sgsaenger** [comment] 2018-05-04 19:29
it works! you're fast :)

**Comment by yancharkin** [comment] 2018-05-04 19:34
Great! Closing this issue.
Sadly for new installers I have to implement new solution (and I have some ideas), but that's a different issue.

**Closed as completed by yancharkin** 2018-05-04 19:34 UTC
