### ISSUE TITLE
DLC support

### ISSUE THREAD

**Issue by Patola** [yancharkin/games_nebula#21] opened 2018-04-10 21:06 UTC
I just bought Dark West on GOG and downloaded it successfully using games_nebula.
However, I also bought its DLC "Scars of Freedom". I noticed it was not installed, and I tried to see if there was any way to install it via games_nebula. Couldn't find any.
Do you plan on having this feature? How would the GUI for it be?

**Comment by yancharkin** [comment] 2018-04-10 22:48
I'd like to implement proper dlc management, but the problem is I own only one game with dlcs (and it's a Windows-only game), so I can't do that. 
But it shouldn't be too hard to write a script for a specific game that will handle dlcs installation.
I'll try to help you, but I need some info:
- is dlc present in download directory (by default: ~/.games_nebula/games/goglib/downloads/hard_west/dlc/hard_west_scars_of_freedom)?
- unzip the dlc installer and post files list
- try to copy unziped files to game directory, after that dlc should be available in the game

**Comment by Patola** [comment] 2018-04-11 23:15
I downloaded the dlc installer and ran it. It asked me for the hard west directory, which in my case is `/jogos/gog/hard_west`. It added the `game/Data_dlc1` under this directory after the gog installer execution. It also seems to have added a few files under `game/HardWest_Data`, namely these:

```
-rw-r--r-- 1 patola patola  13345516 abr 10 17:38 level47
-rw-r--r-- 1 patola patola  32993888 abr 10 17:38 level48
-rw-r--r-- 1 patola patola  23947988 abr 10 17:38 level49
-rw-r--r-- 1 patola patola  16563084 abr 10 17:38 level50
-rw-r--r-- 1 patola patola  21051388 abr 10 17:38 level51
-rw-r--r-- 1 patola patola  33261304 abr 10 17:38 level52
drwx--x--x 6 patola patola      4096 abr 10 17:38 .
-rw-r--r-- 1 patola patola  33132988 abr 10 17:38 level53

``` 
The list of files it added under `game/Data_dlc1` follows:

```
[20:14] [6758] [patola@risadinha game]% ls -latr Data_dlc1 
total 172
drwxr-xr-x 5 patola patola  4096 abr 10 17:38 ..
drwx------ 2 patola patola  4096 abr 10 17:38 Texts
-rw-r--r-- 1 patola patola  2110 abr 10 17:38 cards.tsv
-rw-r--r-- 1 patola patola  1863 abr 10 17:38 buffs_mod.tsv
-rw-r--r-- 1 patola patola 37988 abr 10 17:38 characters.tsv
-rw-r--r-- 1 patola patola  1567 abr 10 17:38 content.dat
-rw-r--r-- 1 patola patola 17616 abr 10 17:38 characters_mod.tsv
-rw-r--r-- 1 patola patola 63843 abr 10 17:38 dialogs.tsv
-rw-r--r-- 1 patola patola  2446 abr 10 17:38 objectives.tsv
-rw-r--r-- 1 patola patola  3525 abr 10 17:38 loot.tsv
-rw-r--r-- 1 patola patola  1767 abr 10 17:38 itemdefs_mod.tsv
-rw-r--r-- 1 patola patola  2443 abr 10 17:38 weapons_mod.tsv
-rw-r--r-- 1 patola patola    87 abr 10 17:38 speakers.tsv
-rw-r--r-- 1 patola patola  3941 abr 10 17:38 shopdefs_mod.tsv
drwx------ 3 patola patola  4096 abr 10 17:38 .
[20:14] [6759] [patola@risadinha game]% ls -latrR Data_dlc1
Data_dlc1:
total 172
drwxr-xr-x 5 patola patola  4096 abr 10 17:38 ..
drwx------ 2 patola patola  4096 abr 10 17:38 Texts
-rw-r--r-- 1 patola patola  2110 abr 10 17:38 cards.tsv
-rw-r--r-- 1 patola patola  1863 abr 10 17:38 buffs_mod.tsv
-rw-r--r-- 1 patola patola 37988 abr 10 17:38 characters.tsv
-rw-r--r-- 1 patola patola  1567 abr 10 17:38 content.dat
-rw-r--r-- 1 patola patola 17616 abr 10 17:38 characters_mod.tsv
-rw-r--r-- 1 patola patola 63843 abr 10 17:38 dialogs.tsv
-rw-r--r-- 1 patola patola  2446 abr 10 17:38 objectives.tsv
-rw-r--r-- 1 patola patola  3525 abr 10 17:38 loot.tsv
-rw-r--r-- 1 patola patola  1767 abr 10 17:38 itemdefs_mod.tsv
-rw-r--r-- 1 patola patola  2443 abr 10 17:38 weapons_mod.tsv
-rw-r--r-- 1 patola patola    87 abr 10 17:38 speakers.tsv
-rw-r--r-- 1 patola patola  3941 abr 10 17:38 shopdefs_mod.tsv
drwx------ 3 patola patola  4096 abr 10 17:38 .

Data_dlc1/Texts:
total 428
-rw-r--r-- 1 patola patola 357210 abr 10 17:38 texts_dlc1_scenario.tsv
-rw-r--r-- 1 patola patola  69371 abr 10 17:38 texts_dlc1_system.tsv
drwx------ 2 patola patola   4096 abr 10 17:38 .
drwx------ 3 patola patola   4096 abr 10 17:38 ..
[20:14] [6760] [patola@risadinha game]% 
```

Sorry to take that long to respond. github did not send me an email telling me of your comment, I am turning on 'watch' on this repository to ensure I will be able to respond you in a timely manner.
I will also look into the code to see if I can do anything by myself.

Thank you for making your software available to all. I am always recommending it on the gamingonlinux forums.

**Comment by Patola** [comment] 2018-04-11 23:19
List of files of the auto-extracting shell script is attached:

```
[20:18] [6763] [patola@risadinha outros]% unzip -v gog_hard_west_scars_of_freedom_dlc_2.3.0.4.sh > /tmp/files.txt
warning [gog_hard_west_scars_of_freedom_dlc_2.3.0.4.sh]:  787400 extra bytes at beginning or within zipfile
  (attempting to process anyway)
[20:18] [6764] [patola@risadinha outros]% 
```
[files.txt](https://github.com/yancharkin/games_nebula/files/1900789/files.txt)

**Comment by yancharkin** [comment] 2018-04-11 23:21
'Games Nebula' should download dlc automatically. Can you check if it's present in the download directory?

**Comment by Patola** [comment] 2018-04-11 23:21
Also, I just started playing this game, so I can afford uninstalling and reinstalling it and its DLC many times if you need to properly test whatever you code. I am also always using the latest code from github.

**Comment by Patola** [comment] 2018-04-11 23:25
It's not, neither under `~/.games_nebula/games/goglib` (recursively) nor `~/.games_nebula/games/mylib`. I had refreshed my library a few times before using the manual installer.

But I didn't turn on the 'download extras' option. Should I do that? Will it re-download every extra from every game after I check this option?

**Comment by yancharkin** [comment] 2018-04-11 23:29
You can try. If you turn it off after installing the game it will not affect other games.

**Comment by yancharkin** [comment] 2018-04-11 23:59
I have one game with dlc: 'Eador - Master of The Broken Work'. I tried to install it and 'Game Nebula' downloaded both main game and dlc (without enabling 'download extras'), so if dlc for 'Hard West' not present in **~/.games_nebula/games/goglib/downloads/hard_west/dlc/hard_west_scars_of_freedom** that means that GOG distribute it differently and it's make things harder.

I'll post setup script a bit later, it's not a proper solution, but still...

**Comment by Patola** [comment] 2018-04-12 00:07
Ok. I tried to remove it via games_nebula but when I clicked the "Remove" button I had this message on the terminal:
```
  File "./games_nebula.py", line 4791, in goglib_setup_game
    + self.goglib_dict_name_to_title[game_name] + "'?"
  File "./games_nebula.py", line 174, in simple_question
    content_area_label = content_area.get_children()[0].get_children()[0].get_children()[1]
AttributeError: 'Image' object has no attribute 'get_children'
```

So I removed it manually with `rm -rf /jogos/gog/hard_west`. Quit games_nebula and launched it again.
Checked 'keep installers' and 'keep extras' to `on`.
It downloaded lots of stuff, including the dlc. It's now downloading the game, 8 minutes to go.

**Comment by Patola** [comment] 2018-04-12 00:17
dlc is `/jogos/download/hard_west/dlc/hard_west_scars_of_freedom/gog_hard_west_scars_of_freedom_dlc_2.3.0.4.sh`
It downloaded successfully. Also installed the game successfully, but did not install the DLC.
Note that for this particular game there are also a few 'extras' that appear on the dlc download directory:

```
[21:16] [6802] [patola@risadinha outros]% ls -latr /jogos/download/hard_west/dlc/hard_west_collectors_pack/extras 
total 362200
drwxr-xr-x 3 patola patola      4096 abr 11 20:43 ..
-rw-r--r-- 1 patola patola  56574351 abr 11 20:44 hard_west_ost_mp3.zip
-rw-r--r-- 1 patola patola  20852177 abr 11 20:44 hard_west_artbook.zip
drwxr-xr-x 2 patola patola      4096 abr 11 20:44 .
-rw-r--r-- 1 patola patola  26690233 abr 11 20:44 hard_west_comic.zip
-rw-r--r-- 1 patola patola 266748152 abr 11 20:46 hard_west_ost_flac.zip

```
What I mean is that if there is a routine to automatically install dlcs it should ignore files like these.

**Comment by yancharkin** [comment] 2018-04-12 00:38
Problem is that dlc is in extras... That isn't right.
I'll try to find a way to resolve this issue, but not today.

**Comment by yancharkin** [comment] 2018-04-12 09:47
First of all that's a strange error:
```
  File "./games_nebula.py", line 4791, in goglib_setup_game
    + self.goglib_dict_name_to_title[game_name] + "'?"
  File "./games_nebula.py", line 174, in simple_question
    content_area_label = content_area.get_children()[0].get_children()[0].get_children()[1]
AttributeError: 'Image' object has no attribute 'get_children'
```
What distro and gtk3 version are you using?
For now you can comment or remove lines 152, 153, 174 and 175 in games_nebula.py to fix this issue.

**Comment by yancharkin** [comment] 2018-04-12 09:47
Looks like 'Keep installers' switch was off first time, right?  If so we don't know for sure that dlc wasn't downloaded during installation, because GN works this way:
- you click 'Install'
- GN download installer (if not exists in download directory)
- GN unpack installer to destination directory
- **GN execute 'setup' script for the game (if exists)**
- GN create additional file (start.sh and others)
- **if 'Keep installers' is off, GN removes everything that was downloaded**

And currently dlcs can be installed automatically only by 'setup' script, which should be created for every game with dlcs.

Try the following:
- switch 'Keep installer' to on (if it is not)
- switch 'Download extras' to off
- remove extras and dlc or move them to another place
- remove game
- click 'Install'
- check if dlc download started (file /jogos/download/hard_west/dlc/hard_west_scars_of_freedom/gog_hard_west_scars_of_freedom_dlc_2.3.0.4.sh created)
- if you have a dlc backup copy, you can abort intallation and move backup copy to its original directory

As a result of this experiment we will know if dlc was downloaded during installation.

**Comment by yancharkin** [comment] 2018-04-12 10:01
**For the next step doesn't matter what results you got in the above experiment, but dlc should present in the download directory:**
download [this archive](https://github.com/yancharkin/games_nebula/files/1902497/hard_west.zip) and unpack it to <GN_ROOT>/scripts/goglib/hard_west or to ~/.games_nebula/scripts/goglib/hard_west and try to reinstall the game.

**Comment by Patola** [comment] 2018-04-13 00:26
@yancharkin made exactly as you told. Removed hard west, set the options you asked, copied the setup file to the hard west directory, and not only it downloaded the DLC but it also automatically installed the DLC to the correct place. Woohoo!

**Comment by yancharkin** [comment] 2018-04-13 08:31
Excellent! Script added to  [goglib_scripts](https://github.com/yancharkin/games_nebula_goglib_scripts) and will be included in the next release. If you have any other games with dlcs you can write scripts for them using this script as example.

Also currently I'm working on a new module that will replace lgogdownloader and, hopefully, allow easier dlcs installation.

**Closed as completed** 2018-04-13 08:31 UTC
